### ISSUE TITLE
Axis IP camera stop responses without error 

### ISSUE THREAD

**Issue by chuong** [borevitzlab/Gigavision#31]
This issue happens to ipcam_test.py (single threaded version) once after a few day. Image query fails to grab an image. There's no error, urllib.urlopen() just waits forever. It happened again this morning in the middle of a panorama. More than half the number of image had been captured, then the program kept waiting to query an image. I had to stop the program by "Ctrl+C" and below is the output from just before the program stop taking more images:
```
....
http://root:admin@10.132.11.32:4442/axis-cgi/com/ptz.cgi?pan=-63.3115&tilt=-2.572
http://root:admin@10.132.11.32:4442/axis-cgi/bitmap/image.bmp?resolution=1280x720&compression=0
Save to /home/chuong/data/PanoFallback/ARB-GV-HILL-1/2015/2015_05/2015_05_18/2015_05_18_07/ARB-GV-HILL-1_2015_05_18_07_00/ARB-GV-HILL-1_2015_05_18_08_08_00_00_0420.jpg
http://root:admin@10.132.11.32:4442/axis-cgi/com/ptz.cgi?pan=-63.3112&tilt=-4.4733
http://root:admin@10.132.11.32:4442/axis-cgi/bitmap/image.bmp?resolution=1280x720&compression=0
Save to /home/chuong/data/PanoFallback/ARB-GV-HILL-1/2015/2015_05/2015_05_18/2015_05_18_07/ARB-GV-HILL-1_2015_05_18_07_00/ARB-GV-HILL-1_2015_05_18_08_08_00_00_0421.jpg
http://root:admin@10.132.11.32:4442/axis-cgi/com/ptz.cgi?pan=-63.3107&tilt=-6.3689
http://root:admin@10.132.11.32:4442/axis-cgi/bitmap/image.bmp?resolution=1280x720&compression=0
^CTraceback (most recent call last):
  File "ipcam_test.py", line 252, in <module>
    ImageFileName = getFileName(PanoFolder, CameraName, i, 'jpg')
  File "ipcam_test.py", line 57, in captureImage2File2
    try:
  File "ipcam_test.py", line 41, in captureImage
    stream = urllib.urlopen(URL_Str)
  File "/home/chuong/anaconda/lib/python2.7/urllib.py", line 87, in urlopen
    return opener.open(url)
  File "/home/chuong/anaconda/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/home/chuong/anaconda/lib/python2.7/urllib.py", line 351, in open_http
    errcode, errmsg, headers = h.getreply()
  File "/home/chuong/anaconda/lib/python2.7/httplib.py", line 1145, in getreply
    response = self._conn.getresponse()
  File "/home/chuong/anaconda/lib/python2.7/httplib.py", line 1073, in getresponse
    response.begin()
  File "/home/chuong/anaconda/lib/python2.7/httplib.py", line 415, in begin
    version, status, reason = self._read_status()
  File "/home/chuong/anaconda/lib/python2.7/httplib.py", line 371, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/home/chuong/anaconda/lib/python2.7/socket.py", line 476, in readline
chuong@marlo-cecs:~/workspace/Gigavision$
'''

**Comment by chuong** [comment]
Just implemented a timeout using urllib2. See if this helps.

**Comment by chuong** [comment]
This seems to be fixed with urllib2 and timeout feature. It can detects when the camera turns on/off in the middle of a panorma.
